"""empty message

Revision ID: b4fc190a5741
Revises: 64c9e128b8d7
Create Date: 2025-12-12 00:00:49.833839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4fc190a5741'
down_revision: Union[str, None] = '64c9e128b8d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientsorm', sa.Column('username', sa.String(), nullable=False))
    op.add_column('clientsorm', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('clientsorm', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('clientsorm', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'clientsorm', ['phone_number'])
    op.create_unique_constraint(None, 'clientsorm', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clientsorm', type_='unique')
    op.drop_constraint(None, 'clientsorm', type_='unique')
    op.drop_column('clientsorm', 'password')
    op.drop_column('clientsorm', 'phone_number')
    op.drop_column('clientsorm', 'is_active')
    op.drop_column('clientsorm', 'username')
    # ### end Alembic commands ###
